image: brospars/docker-mkdocs
pages:
  stage: deploy
  script:
  - pip install -r requirements.txt
  - mkdocs build --site-dir public
  - cd public
  artifacts:
    expire_in: 3 days
    paths:
    - public
  only:
  - main