name: Deploy Staging MkDocs to GitHub Pages

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-staging"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Installer les plugins MkDocs nécessaires
          pip install mkdocs-material mkdocs-macros-plugin mkdocs-exclude mkdocs-awesome-pages-plugin mkdocs-page-pdf==0.1.0 mkdocs-static-i18n==0.52 mkdocs-video mkdocs-glightbox mkdocs-table-reader-plugin

      - name: Build MkDocs staging site
        run: mkdocs build --clean --config-file mkdocs.yml --site-dir site/staging

      - name: Prepare staging folder for GitHub Pages
        run: |
          mkdir -p staging
          cp -r site/staging/* staging/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./staging

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
